### ISSUE TITLE
program crashes

### ISSUE THREAD

**Issue by thor9388** [ChendoChap/Playstation-4-Save-Mounter#13]
Hey there,
I can't seem to be able to get the PS4 Save Mounter to work with me. I load the payload, open ftp, connect the PS4 Save Mounter and it does get connected. After that when I press the setup button, the program freezes doesn't respond. Please could you help me with this. Thank you.

EDIT: When I try to force close the app and let windows restore the app, I get this error,

Unhandeled exception has occurred in your application. If you click continue, the application wil ignore this error and attempt to continue. If you click quit, the application will close immediately.

An established connection was aborted by the software in your host machine.

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by thor9388** [comment]
Hey there,
I can't seem to be able to get the PS4 Save Mounter to work with me. I load the payload, open ftp, connect the PS4 Save Mounter and it does get connected. After that when I press the setup button, the program freezes doesn't respond. Please could you help me with this. Thank you.

EDIT: When I try to force close the app and let windows restore the app, I get this error,

Unhandeled exception has occurred in your application. If you click continue, the application wil ignore this error and attempt to continue. If you click quit, the application will close immediately.

An established connection was aborted by the software in your host machine.

See the end of this message for details on invoking
just-in-time (JIT) debugging instead of this dialog box.

To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Pr0jectN1ne** [comment]
Im getting the same issue too

**Comment by BMomani** [comment]
happened to me all the time 
here is the stacktrace

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException: An invalid argument was supplied
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 size, SocketFlags socketFlags)
   at libdebug.PS4DBG.CheckStatus()
   at libdebug.PS4DBG.GetProcessList()
   at PS4Saves.Main.setupButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)



************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9148 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v2.0.50727/mscorlib.dll
----------------------------------------
Playstation 4 Save Mounter
    Assembly Version: 1.5.0.0
    Win32 Version: 1.5.0.0
    CodeBase: file:///D:/Ps4/Tools/save%20mounter/Playstation%204%20Save%20Mounter.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9147 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Configuration/2.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.9136 (WinRelRS6.050727-9100)
    CodeBase: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Xml/2.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.


```
and sometimes I got this too

```
************** Exception Text **************
System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Send(Byte[] buffer, Int32 size, SocketFlags socketFlags)
   at libdebug.PS4DBG.SendData(Byte[] data, Int32 length)
   at libdebug.PS4DBG.SendCMDPacket(CMDS cmd, Int32 length, Object[] fields)
   at libdebug.PS4DBG.GetProcessList()
   at PS4Saves.Main.setupButton_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

hope this helps you in investigating the issue.
thanks

**Comment by Pmmlabs** [comment]
I've run into this issue too, and solution is to start a game between ps4debug loading and FTP loading. And not to close browser window after it. Also, it's better to take ps4debug payload from 1.4 release.
